Catch exception thrown by MIDI output send() function
This catches the following error caused by wrong MIDI data format:
TypeError: Failed to execute 'send' on 'MIDIOutput': Message is
incomplete.